-- 자신의 id를 parent id로 갖는 아이템이 없음
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
  FROM ITEM_INFO I
 WHERE NOT EXISTS (
    SELECT *
      FROM ITEM_TREE T
     WHERE I.ITEM_ID=T.PARENT_ITEM_ID
 )
 ORDER BY I.ITEM_ID DESC
  