SELECT INS.NAME, INS.DATETIME
  FROM ANIMAL_INS INS
  LEFT OUTER JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID=OUTS.ANIMAL_ID
 WHERE OUTS.ANIMAL_ID IS NULL
 ORDER BY INS.DATETIME
 LIMIT 3
 
# SQL에서 LEFT OUTER JOIN을 사용할 때 WHERE 절의 조건은 JOIN한 결과를 필터링합니다.