SELECT INS.ANIMAL_ID, INS.NAME
  FROM ANIMAL_INS INS
  LEFT OUTER JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID=OUTS.ANIMAL_ID
 WHERE OUTS.ANIMAL_ID IS NOT NULL
   AND INS.DATETIME > OUTS.DATETIME
 ORDER BY INS.DATETIME
  