SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, MAXSIZE - SIZE_OF_COLONY AS YEAR_DEV, A.ID
  FROM ECOLI_DATA A,
       (
         SELECT YEAR(DIFFERENTIATION_DATE) AS YEARB, MAX(SIZE_OF_COLONY) AS MAXSIZE
           FROM ECOLI_DATA
          GROUP BY YEARB
       ) B
 WHERE YEAR(A.DIFFERENTIATION_DATE)=B.YEARB
 ORDER BY YEAR, YEAR_DEV